# gaia accuracy testing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/home/nahmed/git/bacterial-args/migration/sweep/control/snake")
```

load libraries
```{r}
library(gaia)
library(tidyr)
library(dplyr)
library(data.table)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(RColorBrewer)
library(viridis)
library(stringr)
library(purrr)
library(scales)
```

set work dir
```{r}
#setwd("/home/nahmed/git/bacterial-args/migration/sweep_height_long/")
#setwd("/home/nahmed/git/bacterial-args/migration/sweep/control/snake")
```

ggplot theme
```{r}
## ggplot theme

my_theme <- function() {
    theme_classic() +
    theme( 
        plot.title = element_text(color="black", size=12, face="bold"),
        axis.title.x = element_text(color="black", size=20, face="bold", vjust=2),
        axis.title.y = element_text(color="black", size=20, face="bold", vjust=2),
        axis.text=element_text(size=24),
        )
}

options(repr.plot.width=14, repr.plot.height=8)
```

# parse parameters and cost functions

```{r}
parse_params <- function(path) {
  base <- basename(path)
  kind  <- str_match(base, "^(sim|control)_")[,2]
  model <- str_match(base, "^(sim|control)_(ss|eq)_")[,3]
  mu    <- str_match(base, "_mu([0-9.]+e[-+][0-9]+)_")[,2]
  mr    <- str_match(base, "_mr([0-9.]+e[-+][0-9]+)_")[,2]
  pm    <- str_match(base, "_pm([0-9.]+e[-+][0-9]+)_")[,2]
  seed  <- str_match(base, "_seed([0-9]+)")[,2]

  tibble(
    kind  = kind,
    model = model,
    mu    = mu,
    mr    = mr,
    pm    = pm,
    seed  = as.integer(seed)
  )
}

# equal-cost matrix 
eq_cost_mat <- matrix(c(
  0,1,1,
  1,0,1,
  1,1,0
), nrow=3, byrow=TRUE)

# source-sink-ish cost function from migration_rate
get_ss_cost_matrix_from_mr <- function(mr_str) {
  src_sink <- as.numeric(mr_str)
  sink_src <- src_sink / 20
  sink_sink <- sink_src * 10

  matrix(c(
    0,          1/src_sink, 1/src_sink,
    1/sink_src, 0,          1/sink_sink,
    1/sink_src, 1/sink_sink, 0
  ), nrow=3, byrow=TRUE)
}

get_cost_mat <- function(costfunction, model, mr) {
  if (costfunction == "eq") {
    eq_cost_mat
  }
  
  else {
    get_ss_cost_matrix_from_mr(mr)
  } 
}


```

# core functions 

```{r}
get_nodes_sim <- function(trees_path) {
  ts    <- treeseq_load(trees_path)
  nodes <- treeseq_nodes(ts)

  samples <- subset(nodes, is_sample == 1L)
  ok <- samples$population_id >= 0
  samples <- samples[ok, , drop=FALSE]

  # map population_ids
  pop_levels <- sort(unique(samples$population_id))
  state_map  <- setNames(seq_along(pop_levels), pop_levels)
  state_id   <- unname(state_map[as.character(samples$population_id)])

  sample_locations <- as.matrix(data.frame(
    node_id  = samples$node_id,
    state_id = state_id
  ))
  storage.mode(sample_locations) <- "integer"
  colnames(sample_locations) <- c("node_id","state_id")

  list(ts=ts, nodes=nodes, sample_locations=sample_locations)
}

get_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

# run mpr function N times 
mpr_reps <- function(ts, sample_locations, cost_mat, nodes, nrep) {
  node_states_df <- data.frame(
    node_time  = nodes$time,
    node_state = nodes$population_id + 1L
  )

  for (i in seq_len(nrep)) {
    mpr <- treeseq_discrete_mpr(ts, sample_locations, cost_mat) ## mpr object contains certainties across locations for each node; export this in the future 
    est <- treeseq_discrete_mpr_minimize(mpr)
    node_states_df[[paste0("rep", i)]] <- est
  }

  node_states_df$node <- 0:(nrow(node_states_df) - 1L)
  node_states_df
}

```

### scoring functions
```{r}

# scoring GAIA on simulated tree sequence
score_reps_sim_only <- function(sim_locations_path, mpr_reps_output) {
  loc <- read.csv(sim_locations_path) %>%
    mutate(mrca_population = as.integer(str_extract(mrca_population, "[0-9]+")) + 1L) %>%
    select(sample_a, sample_b, bin, position, node,mrca_population)#, node_height_sim)

  loc %>%
    left_join(mpr_reps_output, by = "node") %>%
    rowwise() %>%
    mutate(mode = get_mode(c_across(starts_with("rep"))),
          score = as.integer(mode == mrca_population)) %>%
    ungroup() 
}


score_control <- function(sim_locations_path, control_locations_path) {
  loc <- read.csv(sim_locations_path) %>%
    mutate(mrca_population = as.integer(str_extract(mrca_population, "[0-9]+")) + 1L) %>%
    select(sample_a, sample_b, bin, position, node,mrca_population)#, node_height_sim)
  
  ctrl_loc <- read.csv(control_locations_path) %>%
            rename(ctrl_population = population, ctrl_node = node, ctrl_height = node_height) %>%
            select(-population_entropy, -type) 

  ctrl_loc <- loc %>% left_join(ctrl_loc, by = c("sample_a", "sample_b")) %>%
              mutate(score = as.integer(mrca_population == ctrl_population)) %>% 
              mutate(certainty = case_when(
                mrca_population == 1 ~ X1,
                mrca_population == 2 ~ X2, 
                mrca_population == 3 ~ X3
              ))
  
  return(ctrl_loc)
}


get_scores_one_run_on_sim_ts <- function(ts_sim_path, sim_locations_path, cost_mat, nreps=10) {
  sim_nodes <- get_nodes_sim(ts_sim_path)
  reps <- mpr_reps(sim_nodes$ts, sim_nodes$sample_locations, cost_mat, sim_nodes$nodes, nreps)
  score_reps_sim_only(sim_locations_path, reps)
}

```

# build and organize runs 
```{r}
build_run_table <- function(trees_dir="trees", locs_dir="locations") {

  sim_trees <- list.files(trees_dir, pattern="^sim_(ss|eq).*\\.trees$", full.names=TRUE)
  #control_trees <- list.files(trees_dir, pattern="^sim_(ss|eq).*\\.trees$", full.names=TRUE)
  sim_locs  <- list.files(locs_dir,  pattern="^sim_(ss|eq).*\\.csv$",   full.names=TRUE)
  control_locs  <- list.files(locs_dir,  pattern="^control_(ss|eq).*\\.csv$",   full.names=TRUE)

  sim_trees_df <- bind_cols(tibble(sim_trees=sim_trees), parse_params(sim_trees)) %>% select(-kind)
  #inf_trees_df <- bind_cols(tibble(inf_trees=inf_trees), parse_params(inf_trees)) %>% select(-kind)
  sim_locs_df  <- bind_cols(tibble(sim_locs=sim_locs),   parse_params(sim_locs))  %>% select(-kind)
  control_locs_df  <- bind_cols(tibble(control_locs=control_locs),   parse_params(control_locs))  %>% select(-kind)

  sim_trees_df %>%
    #inner_join(inf_trees_df, by=c("model","mu","mr","pm","seed")) %>%
    inner_join(sim_locs_df,  by=c("model","mu","mr","pm","seed")) %>%
    inner_join(control_locs_df,  by=c("model","mu","mr","pm","seed")) %>%
    arrange(model, pm, mu, mr, seed)
}

```




# scoring sim and inf location estimates (pairwise)
```{r}

runs <- build_run_table("trees", "locations")

scores_control_eq <- pmap_dfr(runs, function(model, mu, mr, pm, seed, sim_locs, control_locs, ...) {

    df <- score_control(
      sim_locations_path = sim_locs, 
      control_locations_path = control_locs
    )

    df %>%
      mutate(
        model = model,
        pm = pm,
        mu = mu,
        mr = mr,
        seed = seed,
        gaia_target = "control",
        costfunction = "eq"
      )
  }
)

scores_sim_eq <- pmap_dfr(runs, function(model, mu, mr, pm, seed, sim_trees, sim_locs, ...) {

    df <- get_scores_one_run_on_sim_ts(
      ts_sim_path = sim_trees,
      sim_locations_path = sim_locs,
      cost_mat = eq_cost_mat,
      nreps = 10
    )

    df %>%
      mutate(
        model = model,
        pm = pm,
        mu = mu,
        mr = mr,
        seed = seed,
        gaia_target = "sim",
        costfunction = "eq"
      )
  }
)


# scores_sim_eq <- scores_sim_eq %>% filter(!is.na(rep1)) ## filter out sims that were reproduced incorrectly 
# scores_control_eq <- scores_control_eq %>% filter(!is.na(ctrl_node))
# 
# scores_control_keep <- scores_control_eq %>%
#   semi_join(scores_sim_eq, by = c("sample_a", "sample_b", "bin", "position", "pm", "mu", "mr", "seed"))
# 
# scores <- merge(scores_sim_eq, scores_sim_eq, by = c("sample_a", "sample_b", "bin", "position", "pm", "mu", "mr", "seed"))
# scores

scores_eq_pairs <- bind_rows(scores_control_eq, scores_sim_eq)

scores_eq_pairs
```

```{r}

scores_eq_pairs <- scores_eq_pairs %>% filter(!is.na(node))

# write.csv(scores_eq_pairs, "scores_eq_pairs_003.csv")
```

# per-bin scores 
```{r}

scores_eq_bin <- scores_eq_pairs %>%
  group_by(model, pm, mu, mr, seed, gaia_target, costfunction, bin, position) %>%
  summarise(
    pbin = mean(score, na.rm = TRUE),
    n_pairs = sum(!is.na(score)),
    mean_node_height_sim = mean(node_height_sim, na.rm = TRUE),
    .groups = "drop"
  )


#write.csv(scores_eq_bin, "scores_eq_bins_002.csv")

```


# per-run scores 

```{r}

scores_eq_runs <- scores_eq_bin %>%
  group_by(model, pm, mu, mr, seed, gaia_target, costfunction) %>%
  summarise(mean_pbin = mean(pbin, na.rm = TRUE), .groups = "drop")


#write.csv(scores_eq_runs, "scores_eq_runs_002.csv")

```



